#!/usr/bin/env bash
#Install nginx web server and Redirection
custom_header="add_header X-Served-By \$HOSTNAME"


sudo apt-get update
sudo apt install nginx -y
sudo vi /etc/nginx/sites-available/default
