#!/usr/bin/env bash
# Display a list of currently running processes in the desired format
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Use ps to retrieve information about processes
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
