#!/usr/bin/env bash
# Display "Best School" 10 times, with a special case on the 9th iteration

# Initialize a counter
counter=0

# Use a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]
do
	if [ $counter -eq 8 ]; then
		# Special case for the 9th iteration
		echo "Best School"
		echo "Hi"
	else
		# Regular case
		echo "Best School"
	fi

	# Increment the counter
	((counter++))
done
