#!/usr/bin/env bash
# Script to display numbers from 1 to 20 with specific messages for certain iterations

# Initialize a counter
counter=1

# Use a while loop to display numbers from 1 to 20
while [ $counter -le 20 ]
do
    case $counter in
	4)
            # Display message for the 4th iteration
            echo -e "4\nbad luck from China"
            ;;
    	9)
            # Display message for the 9th iteration
            echo -e "9\nbad luck from Japan"
            ;;
    	17)
            # Display message for the 17th iteration
            echo -e "17\nbad luck from Italy"
            ;;
    	*)
            # Display the current number for other iterations
            echo $counter
            ;;
    esac

    # Increment the counter
    ((counter++))
done
